/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    ApiExplorer: typeof import('./src/components/api-explorer.vue')['default']
    ApiExplorerContent: typeof import('./src/components/api-explorer-content.vue')['default']
    ApiViewer: typeof import('./src/components/api-viewer.vue')['default']
    ApiViewerContent: typeof import('./src/components/api-viewer-content.vue')['default']
    ApiViewerContentMarkdown: typeof import('./src/components/api-viewer-content-markdown.vue')['default']
    AuroraButton: typeof import('@aurora-design/vue')['AuroraButton']
    AuroraInput: typeof import('@aurora-design/vue')['AuroraInput']
    AuroraMenu: typeof import('@aurora-design/vue')['AuroraMenu']
    AuroraMenuItem: typeof import('@aurora-design/vue')['AuroraMenuItem']
    AuroraWorld: typeof import('@aurora-design/vue')['AuroraWorld']
    BottomView: typeof import('./src/components/bottom-view.vue')['default']
    CodeEditor: typeof import('./src/components/code-editor.vue')['default']
    copy: typeof import('./src/components/api-explorer copy.vue')['default']
    LeftBar: typeof import('./src/components/left-bar.vue')['default']
    OriginEditor: typeof import('./src/components/origin-editor.vue')['default']
    OriginSelector: typeof import('./src/components/origin-selector.vue')['default']
    VanCell: typeof import('vant/es')['Cell']
    VanCellGroup: typeof import('vant/es')['CellGroup']
    VanDivider: typeof import('vant/es')['Divider']
    VanFloatingPanel: typeof import('vant/es')['FloatingPanel']
  }
}
